# Prerequisites: Create docker networks (global and internal), e.g.
# docker network create attack-net-global
# docker network create --internal attack-net-internal
version: "3"
services: 
    kali:
        build: .    # build from Dockerfile
        tty: true 
        volumes: 
          - ./:/root/workspace
        environment: 
            SHELL: /bin/bash
        networks:
          - global
          - internal
    metasploitable: 
        image: tleemcjr/metasploitable2   # from Metasploitable2 docker image
        tty: true
        networks:
          - internal 

networks:
  global:
    external:
      name: attack-net-global 
  internal:
    external:
      name: attack-net-internal
